import React from 'react';

// (articles data should be passed as a prop or imported if it grows larger)
const articlesData = [
    { id: 'time-saving-hacks', title: '5 Time-Saving Hacks for Your Weekly Grocery Trip', snippet: 'Turn a chaotic trip into a quick and efficient mission with these five simple hacks to help you save time at the store.', content: `The weekly grocery run can feel like a marathon...` },
    { id: 'pantry-checklist', title: 'The Ultimate Pantry Checklist: 10 Items You Should Never Run Out Of', snippet: 'A well-stocked pantry is the secret weapon of a stress-free kitchen...', content: `A well-stocked pantry is the secret weapon...` },
    { id: 'meal-planning', title: 'How to Plan a Week of Meals Using Your Grocery List', snippet: 'Meal planning can feel daunting, but it\'s one of the best ways to save money...', content: `Meal planning can feel like a daunting task...` }
];

export const AboutPage = ({ setPage }) => ( <div className="bg-white p-6 md:p-8 rounded-2xl shadow-lg prose max-w-none"><button onClick={() => setPage('home')} className="mb-6 text-blue-600 hover:text-blue-800 font-semibold">&larr; Back to App</button><h2>About CartSpark</h2><p><strong>Our Mission: Smarter Shopping, Not Harder Shopping.</strong></p><p>Welcome to CartSpark, your new grocery list AI companion! We believe that a trip to the grocery store shouldn't be a chore. It should be simple, efficient, and maybe even a little bit fun.</p><p>Using the power of artificial intelligence, CartSpark instantly transforms your scattered shopping list into a perfectly organized, aisle-by-aisle path through the store.</p><h4>With CartSpark, you can:</h4><ul><li><strong>Sort Instantly:</strong> Automatically categorize your items into Produce, Dairy, Pantry, and more.</li><li><strong>Get Inspired:</strong> Use our "Get Meal Idea" feature to generate a simple recipe based on what's already on your list.</li><li><strong>Never Forget an Item:</strong> Our "Suggest" feature intelligently recommends related items you might have missed.</li><li><strong>Shop Your Way:</strong> Edit, add, delete, and check off items on the fly with a simple, interactive list that saves to your device.</li></ul><p>Our goal is to give you back your time and mental energy. Thank you for joining us on this journey!</p></div> );
export const PrivacyPolicyPage = ({ setPage }) => ( <div className="bg-white p-6 md:p-8 rounded-2xl shadow-lg prose max-w-none"><button onClick={() => setPage('home')} className="mb-6 text-blue-600 hover:text-blue-800 font-semibold">&larr; Back to App</button><h2>Privacy Policy for CartSpark</h2><p><em>Last Updated: July 16, 2025</em></p><p>Your privacy is important to us. This Privacy Policy explains how CartSpark collects, uses, and protects your information.</p><h3>1. Information We Collect</h3><p>For logged-in users, we store your grocery lists and preferences in our secure cloud database. For guests, CartSpark uses your browser's <code>localStorage</code> to save information directly on your device. We store:</p><ul><li><strong>Your Current Grocery List:</strong> Item names, categories, and checked status.</li><li><strong>Ignored Suggestions:</strong> A temporary record of AI suggestions you've seen.</li></ul><p><strong>For logged-in users, your data is protected by our security rules so only you can access it. For guest users, this information is stored exclusively on your device's browser.</strong></p><h3>2. Third-Party Services</h3><p>CartSpark uses these services:</p><ul><li><strong>Google Gemini API:</strong> To power AI features. Your list content is sent to Google for processing, governed by Google's Privacy Policy.</li><li><strong>Google AdSense:</strong> To display ads for non-logged-in users. Google may use cookies to serve ads. You can opt out in <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer">Google's Ads Settings</a>.</li><li><strong>Affiliate Links:</strong> If you click affiliate links (e.g., Instacart, Uber Eats) and make a purchase, we may earn a commission.</li></ul><h3>3. Clearing Your Data</h3><p>Clicking the "Start New List" or "Start Over" button will permanently delete your active list data. You can delete your account and all associated data by contacting us.</p><h3>4. Contact Us</h3><p>If you have questions, please contact us at: <a href="mailto:contactus@cartspark.io">contactus@cartspark.io</a></p></div> );
export const BlogPage = ({ setSelectedArticle, setPage }) => ( <div className="bg-white p-6 md:p-8 rounded-2xl shadow-lg"><button onClick={() => setPage('home')} className="mb-6 text-blue-600 hover:text-blue-800 font-semibold">&larr; Back to App</button><h2 className="text-3xl font-bold text-center mb-8">CartSpark Blog</h2><div className="space-y-8">{articlesData.map(article => ( <div key={article.id} className="p-6 border rounded-lg"><h3 className="text-2xl font-semibold text-gray-800">{article.title}</h3><p className="mt-2 text-gray-600">{article.snippet}</p><button onClick={() => setSelectedArticle(article)} className="mt-4 text-blue-600 font-semibold hover:underline">Read more &rarr;</button></div> ))}</div></div> );
export const ArticlePage = ({ article, setSelectedArticle }) => ( <div className="bg-white p-6 md:p-8 rounded-2xl shadow-lg prose max-w-none"><button onClick={() => setSelectedArticle(null)} className="mb-6 text-blue-600 hover:text-blue-800 font-semibold">&larr; Back to Blog</button><h2 className="text-3xl font-bold">{article.title}</h2><div className="mt-6 text-gray-700" style={{whiteSpace: 'pre-line'}}>{article.content}</div></div> );
